name: delamane dev deployment
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:     
    - uses: actions/checkout@v2
    - name: setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: build api
      run: |
            dotnet restore DELAMANE-BOT/DELAMANE-BOT.csproj
            dotnet build DELAMANE-BOT/DELAMANE-BOT.csproj --configuration Development
            dotnet publish DELAMANE-BOT/DELAMANE-BOT.csproj -o ./staging/app/DELAMANE-BOT /p:EnvironmentName=Development -r linux-x64
            cd ./staging/app/DELAMANE-BOT
            ./DELAMANE-BOT ${{ secrets.AWS_ACCESS_KEY_ID }} ${{ secrets.AWS_SECRET_ACCESS_KEY }} 